// Generated by Haxe 4.1.1
#ifndef INCLUDED_invoices_Invoices
#define INCLUDED_invoices_Invoices

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_16d41c6fc5b8bf5d
#define INCLUDED_16d41c6fc5b8bf5d
#include "maglev/MagLev.h"
#endif
HX_DECLARE_CLASS1(invoices,Invoices)

namespace invoices{


class HXCPP_CLASS_ATTRIBUTES Invoices_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Invoices_obj OBJ_;
		Invoices_obj();

	public:
		enum { _hx_ClassId = 0x1e40d56c };

		void __construct( ::maglev::MagLev maglev);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="invoices.Invoices")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"invoices.Invoices"); }
		static ::hx::ObjectPtr< Invoices_obj > __new( ::maglev::MagLev maglev);
		static ::hx::ObjectPtr< Invoices_obj > __alloc(::hx::Ctx *_hx_ctx, ::maglev::MagLev maglev);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Invoices_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Invoices",46,68,e5,8a); }

		 ::maglev::MagLev maglev;
		void registerMyMethods();
		::Dynamic registerMyMethods_dyn();

};

} // end namespace invoices

#endif /* INCLUDED_invoices_Invoices */ 
